[graph]
targets = []
all-features = true

[advisories]
version = 2
ignore = []

[bans]
multiple-versions = "deny"
wildcards = 'deny'
deny = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"

[licenses]
# We want really high confidence when inferring licenses from text
confidence-threshold = 0.93
allow = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "MIT",
    "MPL-2.0",
    "BSD-3-Clause",
    "ISC",
]